import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRef, useState } from 'react'

export default function Home() {
  const [tokenId, setTokenId] = useState<number>(1)
  const inputEl = useRef<HTMLInputElement>(null)

  return (
    <>
      <Head>
        <title>pNouns Unrevealed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ paddingBottom: '5rem' }}>pNouns Unrevealed</h1>

        <form
          className="row g-3"
          onSubmit={(e) => {
            e.preventDefault()
            const value = Number(inputEl.current?.value)
            if (Number.isFinite(value)) {
              setTokenId(value)
            }
          }}
        >
          <div className="col">
            <input type="text" className="form-control" placeholder="id" ref={inputEl} />
          </div>
          <div className="col">
            <button type="submit" className="btn btn-primary mb-3" formAction="/images">
              Show
            </button>
          </div>
          {Number.isFinite(tokenId) && (
            <div className="col">
              <a href={`/images/${tokenId}.svg`} target="_blank" rel="noreferrer">
                <Image src={`/images/${tokenId}.svg`} alt={`${tokenId}.svg`} width={350} height={350} />
              </a>
            </div>
          )}
        </form>
      </main>
    </>
  )
}
